version: "3"

services:
  mongodb:
    image: 'mongo'
    container_name: 'house-browser-db'
    environment:
      - MONGO_INITDB_DATABASE=house-browser
      - MONGO_INITDB_ROOT_USERNAME=estatesAdmin
      - MONGO_INITDB_ROOT_PASSWORD=estatesPass
    volumes:
      - ./common/dbinit:/docker-entrypoint-initdb.d
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
